"""
LangGraph shared state definition.
AgentState is the single TypedDict passed between all nodes in the graph.
Every node receives the full state and returns a partial update dict.
"""

from typing import Annotated, List, Optional, TypedDict
from langgraph.graph.message import add_messages


class MarketEvent(TypedDict):
    """A structured market intelligence event detected by the Grok scanner."""
    event_id: str
    channel: str                        # Redis channel this was published to
    source: str                         # "grok_x_search" | "grok_web_search"
    timestamp: str                      # ISO 8601
    category: str                       # "supply_chain" | "geopolitical" | "macro" | "sentiment"
    symbols_affected: List[str]         # Tickers likely impacted
    companies_affected: List[str]
    disruption_severity: str            # "low" | "medium" | "high" | "critical"
    confidence: float                   # 0.0 – 1.0
    summary: str                        # One-paragraph qualitative summary
    source_url: Optional[str]
    source_handle: Optional[str]
    raw_content: str


class TradeSignal(TypedDict):
    """A trade signal generated by the supervisor or ingestion node."""
    signal_id: str
    symbol: str
    direction: str                      # "buy" | "sell"
    rationale: str
    confidence: float
    suggested_qty: int
    suggested_limit_price: Optional[float]
    generated_by: str                   # LangGraph node name
    timestamp: str


class TradeExecution(TypedDict):
    """Record of a trade submitted to Alpaca."""
    signal_id: str
    order_id: str
    symbol: str
    qty: int
    side: str
    order_type: str
    time_in_force: str
    limit_price: Optional[float]
    status: str                         # Alpaca order status
    filled_price: Optional[float]
    filled_at: Optional[str]
    timestamp: str


class AgentState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    LangGraph merges partial update dicts returned by each node.
    """
    # ── Message history (LangGraph managed accumulator) ────────────────
    messages: Annotated[list, add_messages]

    # ── Event pipeline ─────────────────────────────────────────────────
    market_events: List[MarketEvent]
    trade_signals: List[TradeSignal]
    trade_executions: List[TradeExecution]

    # ── Portfolio / risk state ─────────────────────────────────────────
    current_portfolio_value: float
    peak_portfolio_value: float
    drawdown_pct: float

    # ── Kill switch ────────────────────────────────────────────────────
    kill_switch_active: bool
    execution_enabled: bool

    # ── Orchestration control ──────────────────────────────────────────
    next_node: str          # Which node the supervisor wants to activate
    error: Optional[str]   # Last error message (if any)
    iteration_count: int   # How many full loops the graph has completed


def initial_state() -> AgentState:
    """Return a clean initial AgentState for a new agent run."""
    return AgentState(
        messages=[],
        market_events=[],
        trade_signals=[],
        trade_executions=[],
        current_portfolio_value=0.0,
        peak_portfolio_value=0.0,
        drawdown_pct=0.0,
        kill_switch_active=False,
        execution_enabled=False,   # Fail-closed: must be explicitly enabled
        next_node="ingestion",
        error=None,
        iteration_count=0,
    )
